### ISSUE TITLE
前端项目打包后没有prod.env.js文件

### ISSUE THREAD

**Issue by fengpan0403** [elunez/eladmin-web#45]
1、打包项目：不管是将项目部署到 ngnix 还是其他服务器，第一步都是将项目打包，使用命令 npm run build
2、上传文件：打包完成后会在根目录生成 dist 文件夹，我们需要将他上传到服务器中，可使用工具 BvSshClient
3、修改接口地址：将 prod.env.js 里面的 bash_api 改成自己生产环境的后端接口地址，注意：如果是IP需设置外网IP
4、配置 ngnix：在 nginx/conf/nginx.conf 修改配置（配置文件路径可能会不同）

打完包后没有 prod.env.js 文件，没办法修改后端接口地址

**Comment by keygod** [comment]
@fengpan0403 打包前修改
