### ISSUE TITLE
新增模块提示api访问404

### ISSUE THREAD

**Issue by esinhee** [elunez/eladmin-web#49]
新增模块，用代码生成工具生成的代码。然后对照现有模块进行修改，基本上是一致了。但是访问的时候还是提示/api/xxx无法访问。原来以为是后台没有权限，但是使用admin登陆也是一样的。debug了，发现没有找到后台。请问这个问题到底是哪里错误了？谢谢。

**Comment by elunez** [comment]
请确保不是在代码生成器中新增的模块，不然无法使用，如果要新增模块请手动操作，新增模块的时候保证包名一致，并且在 system模块中引入新增的模块

**Comment by esinhee** [comment]
@elunez 老哥，在升2.3之前用代码生成器调成功了，也不报错。同步到2.3之后不知道哪里被覆盖才无法访问的。能不能把代码生成器的问题点说一下呢？
