### ISSUE TITLE
三级菜单无法缓存,该怎么做

### ISSUE THREAD

**Issue by luojr18** [elunez/eladmin-web#51]

**Comment by elunez** [comment]
在菜单管理中添加菜单，然后设置缓存，菜单不可见。你试试

**Comment by luojr18** [comment]
我的菜单是要显示的，设置不可见不能够啊

**Comment by elunez** [comment]
不可见只是在左侧隐藏，又不是打不开

**Comment by luojr18** [comment]
左侧不可见，那我要进入这个页面，通过什么方式呢

**Comment by MikuBlog** [comment]
@luojr18 通过JavaScript的方式进入即可

如：`this.$router.push(菜单地址)`
