### ISSUE TITLE
后台登陆界面的验证码接口出现502

### ISSUE THREAD

**Issue by Fomovet** [elunez/eladmin-web#55]
Chrome控制台错误信息：
1、Failed to load resource: the server responded with a status of 502 (Bad Gateway)
2、Access to XMLHttpRequest at 'https://api.auauz.net/auth/code' from origin 'https://auauz.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by elunez** [comment]
> Chrome控制台错误信息：
> 1、Failed to load resource: the server responded with a status of 502 (Bad Gateway)
> 2、Access to XMLHttpRequest at 'https://api.auauz.net/auth/code' from origin 'https://auauz.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

可以网上搜搜 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
