### ISSUE TITLE
修改主题颜色的一些问题

### ISSUE THREAD

**Issue by MikuBlog** [elunez/eladmin-web#60]
修改主题颜色时菜单栏字体颜色和标签栏颜色不变。我建议改变主题颜色时可以改变更多地方颜色。

可以参考我的后台管理模板：[https://xzadmin.xuanzai.top](url)

**Comment by elunez** [comment]
> 修改主题颜色时菜单栏字体颜色和标签栏颜色不变。我建议改变主题颜色时可以改变更多地方颜色。
> 
> 可以参考我的后台管理模板：[https://xzadmin.xuanzai.top](url)

业余前端的我，暂时不考虑这种功能
