### ISSUE TITLE
搜索菜单组件在ipad上失效

### ISSUE THREAD

**Issue by MikuBlog** [elunez/eladmin-web#62]
描述：ipad的chrome、safari浏览器打开后，横屏状态点击搜索菜单icon，无法调出输入法进行输入搜索操作。

截图：
![image](https://user-images.githubusercontent.com/43233731/71463493-88909600-27f1-11ea-9dcd-2f90ae57a7e1.png)

**Comment by elunez** [comment]
> 描述：ipad的chrome、safari浏览器打开后，横屏状态点击搜索菜单icon，无法调出输入法进行输入搜索操作。
> 
> 截图：
> ![image](https://user-images.githubusercontent.com/43233731/71463493-88909600-27f1-11ea-9dcd-2f90ae57a7e1.png)

可以在 https://github.com/PanJiaChen/vue-element-admin 提 issues

**Comment by MikuBlog** [comment]
我初步研究，发现`element-ui`的`el-select`组件，在移动端搜索的状态下都是无法调出键盘的。该问题已经向`element-ui`官方提出。我建议可以用别的插件代替~
