### ISSUE TITLE
为什么分页页码从 0 开始

### ISSUE THREAD

**Issue by ijliym** [elunez/eladmin-web#63]
为什么前端分页页码从 0 开始，而后台计算之前却要加 1呢？直接从 1 开始不就行了吗？

前端
```js
getQueryParams: function() {
  return {
    page: crud.page.page - 1,
    size: crud.page.size,
    sort: crud.sort,
    ...crud.query,
    ...crud.params
  }
}
```

后台
```java
int[] startEnd = PageUtil.transToStartEnd(page + 1, size);
```

**Comment by elunez** [comment]
> 为什么前端分页页码从 0 开始，而后台计算之前却要加 1呢？直接从 1 开始不就行了吗？
> 
> 前端
> 
> ```js
> getQueryParams: function() {
>   return {
>     page: crud.page.page - 1,
>     size: crud.page.size,
>     sort: crud.sort,
>     ...crud.query,
>     ...crud.params
>   }
> }
> ```
> 
> 后台
> 
> ```java
> int[] startEnd = PageUtil.transToStartEnd(page + 1, size);
> ```

这个是 hutool 里面约定的，  而我们默认用的是  Pageable  ，它是从0开始的
