### ISSUE TITLE
菜单管理报错

### ISSUE THREAD

**Issue by sxhjlzl** [elunez/eladmin-web#65]
![1578326675011](https://user-images.githubusercontent.com/12149913/71830263-5defe880-30e1-11ea-97ab-7c70a5b5278a.jpg)
修改这个文件下面
src/components/SvgIcon/index.vue
这段代码中的 iconClass:{type:null} 就不报错了，这个是什么原因
props: {
    iconClass: {
      type: String,
      required: true
    },
    className: {
      type: String,
      default: ''
    }
  },

**Comment by elunez** [comment]
> ![1578326675011](https://user-images.githubusercontent.com/12149913/71830263-5defe880-30e1-11ea-97ab-7c70a5b5278a.jpg)
> 修改这个文件下面
> src/components/SvgIcon/index.vue
> 这段代码中的 iconClass:{type:null} 就不报错了，这个是什么原因
> props: {
> iconClass: {
> type: String,
> required: true
> },
> className: {
> type: String,
> default: ''
> }
> },

![image](https://user-images.githubusercontent.com/42142420/71869196-1fdbde80-314c-11ea-993e-327cafdbacc7.png)
