### ISSUE TITLE
vue页面应该尽可能用组件的方式开发，这样代码会非常清晰方便维护，还有可能复用

### ISSUE THREAD

**Issue by zyd** [elunez/eladmin-web#73]
一个页面的的新增、修改、详情等应该分别写成单独的组件，然后再index.vue中引入，页面功能复杂还可以拆分成更多的组件，这样写出来的代码非常容易读懂，js、css的命名也可以更自由。我们项目刚开始用vue的时候也是一个功能就一个vue文件，代码多了非常乱，后来拆分成组件之后开发和维护方便多了。

**Comment by elunez** [comment]
简单的页面没必要这样拆分，复杂页面可以这样
