### ISSUE TITLE
点击新增外链菜单怎么不跳出当前页面？

### ISSUE THREAD

**Issue by LvXinPeng** [elunez/eladmin-web#76]
点击新增外链菜单怎么不跳出当前页面？~
只在当前页面的右侧展示呢？这个怎么改呢？谢谢~

**Comment by elunez** [comment]
> 点击新增外链菜单怎么不跳出当前页面？~
> 只在当前页面的右侧展示呢？这个怎么改呢？谢谢~

模仿源码中的SQl监控页面
