### ISSUE TITLE
新增外部菜单时页面报route config "component" for path: http://www.baidu.com cannot be a string id. Use an actual component instead.

### ISSUE THREAD

**Issue by akonxiaomixia** [elunez/eladmin-web#89]
`
![image](https://user-images.githubusercontent.com/23638346/78734362-a20db600-797a-11ea-828d-ee65f84cf10c.png)
![image](https://user-images.githubusercontent.com/23638346/78737052-3844da80-7981-11ea-8457-884ae390ad35.png)
这个路由怎么解决？
`

**Comment by elunez** [comment]
外部菜单
![image](https://user-images.githubusercontent.com/42142420/79933064-7eba2f00-8481-11ea-8734-7c1414e88984.png)
