### ISSUE TITLE
代码运行后，浏览器访问报错 Error: Cannot find module '@/views/login'

### ISSUE THREAD

**Issue by rubekid** [elunez/eladmin-web#91]
vue-router.esm.js:1897 Error: Cannot find module '@/views/login'
    at webpackEmptyContext (main.js:75)
    at routers.js:28

请问nodejs 的版本有关吗，nodejs 版本v12.16.2

**Comment by elunez** [comment]
> vue-router.esm.js:1897 Error: Cannot find module '@/views/login'
> at webpackEmptyContext (main.js:75)
> at routers.js:28
> 
> 请问nodejs 的版本有关吗，nodejs 版本v12.16.2

https://github.com/PanJiaChen/vue-element-admin/issues/3127

**Comment by elunez** [comment]
已修复
